import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import itertools

def corr_cellpair(data):
    # make sure cell_id are column names
    correlation = {}
    columns = data.columns.tolist()
    
    for col_a, col_b in itertools.combinations(columns, 2):
        correlation[f'{col_a}_{col_b}'] = pearsonr(data.loc[:, col_a], data.loc[:, col_b])
                
    result = pd.DataFrame.from_dict(correlation, orient = 'index')
    result.columns = ['PCC', 'p-value']
    
    
    return result['PCC'].to_frame()

def get_corr(data, reg_type = 'nonreg'):
    
    label = data['cst1'][['cs_id','animalID']]
    animal_list = list(label.animalID.unique())
    session_list = list(data.keys())
        
    # calculate Pearson correlation
    pooled_corr = pd.DataFrame()
    for i in session_list:
        session_corr = pd.DataFrame()
        grouped = data[i].groupby('animalID')
        for j in animal_list:
            dat = grouped.get_group(j)
            if reg_type == 'reg':
                df = dat[dat.cs_id.isin(label.cs_id)].copy() 
                # used only if registed across sessions 
            else:
                df = dat.copy()
            if len(df) > 1: # check if there are at least two cells for correlation calculation
                print(f'{len(df)}')
                df = df.drop(columns = ['cs_id','animalID','session','aveT','t_ext','t_inh'])    
                corr = corr_cellpair(df.T.dropna())
                
                # keep the pair id to find the pair with highest corr and their traces
                corr = corr.reset_index().rename(columns = {'PCC': i, 'index': f'{i}_pair' }) 
                
                corr[f'animalID_{i}'] = j # Add animalID here
                
                session_corr = pd.concat([session_corr, corr], axis = 0)
            else:
                print(f'{len(df)}')
                pass
        
        session_corr = session_corr.reset_index(drop = True)    
        pooled_corr = pd.concat([pooled_corr, session_corr], axis = 1)   
    
    # Fill NaN ID with empty string
    pooled_corr = pooled_corr.fillna('')
    return pooled_corr

# Load files containing signal, residual, or concatenated traces (generated by SignalResidualTrace.py)
trace_dict = np.load("filepath", allow_pickle = True).item()
trace_corr = get_corr(trace_dict)
